# See https://pre-commit.com for more hooks
repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.11.9
    hooks:
      - id: ruff
        name: ruff-fix
        args:
          - --fix
      - id: ruff
        name: ruff-check
        args:
          - .
        pass_filenames: false
      - id: ruff-format

  - repo: https://github.com/facebook/pyrefly-pre-commit
    rev: 0.0.1
    hooks:
      - id: pyrefly-typecheck-system
        name: Pyrefly (type checking)
        entry: .venv/bin/pyrefly
        args: ["check"]
